name: Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI_NODE_TOTAL: 2
  CI_NODE_CPU_CORES: 2
  RAILS_ENV: test

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      actions: read
    strategy:
      fail-fast: false
      matrix:
        ci_rspec_process_total: [4]
        ci_rspec_process_index: ['0,1', '2,3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup DB
        run: bundle exec rails "parallel:setup[${CI_NODE_CPU_CORES}]"
      - name: Run rspec in parallel
        run: bundle exec parallel_rspec -n ${{ matrix.ci_rspec_process_total }} --only-group ${{ matrix.ci_rspec_process_index }}
      - name: Upload coverage/.resultset.json
        uses: actions/upload-artifact@v4
        with:
          name: coverage-resultset-json-${{ matrix.ci_node_index }}
          path: coverage/.resultset.json
          include-hidden-files: true

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    if: success() || failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Download all coverage resultsets
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-resultset-json-*
          path: ${{ runner.temp }}/coverages
      - name: Aggregate all coverage resultsets
        run: bundle exec rails runner "require 'simplecov'; SimpleCov.collate(Dir['${{ runner.temp }}/coverages/**/.resultset.json'], 'rails')"
      - name: Coverage Report by octocov
        uses: k1LoW/octocov-action@v1
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
