name: Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI_NODE_TOTAL: 2
  CI_NODE_CPU_CORES: 2
  RAILS_ENV: test

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      actions: read
    strategy:
      fail-fast: false
      matrix:
        ci_node_index: [0, 1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Download previous JUnit XML reports
        uses: actions/download-artifact@v4
        with:
          pattern: junit-xml-reports-${{ matrix.ci_node_index }}
          path: ${{ runner.temp }}
      - name: Place previous JUnit XML reports in test_results
        run: |
          if [ -e ${{ runner.temp }}/junit-xml-reports-${{ matrix.ci_node_index }} ]; then
            mkdir -p test_results
            mv ${{ runner.temp }}/junit-xml-reports-${{ matrix.ci_node_index }}/* test_results/
            find test_results/ -type f -name "*.xml" | sed 'p;s/.xml/_prev.xml/' | xargs -n2 mv
            bundle exec rails runner "Dir.glob('test_results/**/*.xml').each { |path| File.write(path, Nokogiri(File.read(path)).tap { _1.css('testcase:has(failure)').remove }.to_s) }"
          fi
      - name: Download previous spec/examples.txt
        uses: actions/download-artifact@v4
        with:
          pattern: examples-${{ matrix.ci_node_index }}
          path: ${{ runner.temp }}
      - name: Check whether only failed tests should be re-run
        id: failed-tests-only
        run: |
          if [ -f ${{ runner.temp }}/examples-${{ matrix.ci_node_index }}/examples.txt ]; then
            mv ${{ runner.temp }}/examples-${{ matrix.ci_node_index }}/examples.txt spec/examples.txt
            sudo chown runner:runner spec/examples.txt
            echo "value=true" >> $GITHUB_OUTPUT
          fi
      - name: Download JUnit XML reports for default branch
        if: ${{ !steps.failed-tests-only.outputs.value }}
        uses: dawidd6/action-download-artifact@v5
        with:
          name: junit-xml-reports-[0-9]+
          name_is_regexp: true
          path: ${{ runner.temp }}/default-branch-junit-xml-reports
          branch: ${{ github.event.repository.default_branch }}
          workflow_conclusion: success
        continue-on-error: true
      - name: Split tests by timings
        if: ${{ !steps.failed-tests-only.outputs.value }}
        uses: r7kamura/split-tests-by-timings@v0
        id: split-tests
        with:
          reports: ${{ runner.temp }}/default-branch-junit-xml-reports
          glob: spec/**/*_spec.rb
          index: ${{ matrix.ci_node_index }}
          total: ${{ env.CI_NODE_TOTAL }}
      - name: Setup DB
        run: bundle exec rails "parallel:setup[${CI_NODE_CPU_CORES}]"
      - name: Run rspec in parallel
        if: ${{ !steps.failed-tests-only.outputs.value }}
        run: bundle exec parallel_rspec -n $CI_NODE_CPU_CORES ${{ steps.split-tests.outputs.paths }}
      - name: Re-run rspec only failures
        if: ${{ steps.failed-tests-only.outputs.value }}
        run: bundle exec rspec --only-failures
      - name: Upload coverage/.resultset.json
        if: ${{ !steps.failed-tests-only.outputs.value }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-resultset-json-${{ matrix.ci_node_index }}
          path: coverage/.resultset.json
          include-hidden-files: true
      - name: Upload JUnit XML reports
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml-reports-${{ matrix.ci_node_index }}
          path: test_results
          if-no-files-found: ignore
      - name: Upload spec/examples.txt
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: examples-${{ matrix.ci_node_index }}
          path: spec/examples.txt
          if-no-files-found: ignore

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    if: success() || failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Download all coverage resultsets
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-resultset-json-*
          path: ${{ runner.temp }}/coverages
      - name: Aggregate all coverage resultsets
        run: bundle exec rails runner "require 'simplecov'; SimpleCov.collate(Dir['${{ runner.temp }}/coverages/**/.resultset.json'], 'rails')"
      - name: Coverage Report by octocov
        uses: k1LoW/octocov-action@v1
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  report-failed-tests:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: true
    permissions:
      contents: read
      pull-requests: write
    if: success() || failure()
    env:
      REVIEWDOG_JSON_FILE_NAME: rspec_reviewdog.jsonl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.20.0
      - name: Download all JUnit XML reports
        uses: actions/download-artifact@v4
        with:
          pattern: junit-xml-reports-*
          path: ${{ runner.temp }}/junit-xml-reports
      - name: Generate RSspec reviewdog json
        env:
          JUNIT_XML_FILE_PATH_PATTERN: ${{ runner.temp }}/junit-xml-reports/**/*.xml
          REVIEWDOG_JSON_FILE_PATH: ${{ runner.temp }}/${{ env.REVIEWDOG_JSON_FILE_NAME }}
        run: bundle exec ruby scripts/generate_rspec_reviewdog_json.rb
      - name: Run rspec reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
          REVIEWDOG_JSON_FILE_PATH: ${{ runner.temp }}/${{ env.REVIEWDOG_JSON_FILE_NAME }}
        run: |
          cat $REVIEWDOG_JSON_FILE_PATH | reviewdog -f=rdjsonl -reporter=github-check
